### ISSUE TITLE
[commentaires] interface/trans

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#1]
Les fichiers [trans.py](https://github.com/mkRPGDev/mkRPG/blob/master/src/interface/trans.py) et [trans.c](https://github.com/mkRPGDev/mkRPG/blob/master/src/interface/trans.c) ne sont pas suffisamment commentés : 
Dans trans.py : 
- il manque un docstring en début de package dans le but d'expliquer ce qu'il fait et pourquoi il est utile
- que signifie `dll = CDLL("./trans.a")`(pour executer le code C d'a coté ?) 
- que fait la fonction `prod ` ?
- pour la fonction `applyMatrix` il y a bien un docstring qui explique la fonction, mais le code suivant n'est pas très compréhensible à la lecture
```
if len(m)==2: m=(m[0][0], m[0][1], m[1][0], m[1][1])
    d = m[0]*m[3]-m[1]*m[2]
    if not d: raise ValueError("Non-inversible matrix")
    im = (m[3]/d, -m[1]/d, -m[2]/d, m[0]/d)
    w,h = surf.get_size()
    x1,y1 = prod(m, (w, 0))
    x2,y2 = prod(m, (0, h))
    x3,y3 = prod(m, (w, h))
    xm = min(0, x1, x2, x3)
    ym = min(0, y1, y2, y3)
    xn = max(0, x1, x2, x3)
    yn = max(0, y1, y2, y3)
    ret = pygame.Surface((xn-xm+1, yn-ym+1)).convert_alpha()
    ars = pygame.surfarray.pixels2d(surf)
    ard = pygame.surfarray.pixels2d(ret)
    dll.trans(ars.ctypes.data, len(ars), len(ars[0]), ard.ctypes.data, len(ard), len(ard[0]),
        c_double(im[0]), c_double(im[1]), c_double(im[2]), c_double(im[3]), int(xm), int(ym)) 
```
Score Pylint : -37.60/10 (exécutez `pylint trans.py`)

Dans trans.c : 
-  pas commentaires pour [doxygen ](http://franckh.developpez.com/tutoriels/outils/doxygen/)
- code commenté peut-être en début de package

**Comment by mcoudriau** [comment]
Le mauvais score était surtout du au import * sur ctypes qui contient de très nombreux types. Fichier commenté et amélioré, cf framateam pour comment le tester.
