### ISSUE TITLE
[Review] interface/utils.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#10]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/interface/utils.py) est bien commenté mais il manque quelques détails : 
- un docstring de description global du module 
- la fonctionne testCoord ne fonctionne surement pas car les fonctions `cell_to_point` et `point_to_cell` ne sont plus définies dans cette version d'utils.py. 

Le fichier a subi de changements que je ne comprends pas. Les Rect List ne sont plus utilisées, et le WalkableGraph est réapparu. 

Code pylint : 1.23/10 (surtout dû aux noms de variables de type `x, y`des systèmes de coordonnées, mais c'est tout à fait normal)

**Comment by ismailbennani** [comment]
Le code a été mis a jour, WalkableGraph est maintenant une methode de la classe Map du fichier shared/world.py. La fonction testCoord a été supprimée.

78ba5a032a93ca1ae1ad8f459f660e445089f5a5
