### ISSUE TITLE
[Review] interface/interface.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#11]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/interface/interface.py) est bien commenté mais je ne comprends pas quelque chose : 
Les méthodes `repaint`, `setPerso`,`init`, `end`,` getEvent` ne sont pas programmées. Est-ce normal car c'est une classe dite "dummy" ? 

Code pylint : 3.33/10 (surtout dû aux docstring manquant des méthodes évoquées ci-dessus)

**Comment by ismailbennani** [comment]
Cette classe est la classe de base pour toutes les interfaces, le fait que ces fonctions ne fassent rien n'empêche pas le client de tourner. La classe correspond a une interface complètement absente et elle sert a tester les autres parties du projet sans lancer pygame ou ncurse
