### ISSUE TITLE
[Review] interface/interactions.py & management/actions.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#12]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/master/src/interface/interactions.py) est bien commenté mais il manque quelques détails : 
- un docstring pour la fonction `load` mais surtout expliquer ce qu'est `dat`
- le Snake est hard-codé à la dernière ligne `registerInteractions("../Test/Snake/")`

Code pylint : 0.91/10 (surtout dû attribute-defined-outside-init de la classe)

**Comment by JulesKzl** [comment]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/master/src/management/actions.py) est bien commenté mais il manque quelques détails : 
- un docstring pour la fonction `load` mais surtout expliquer ce qu'est `dat`
- expliciter les paramètres des fonctions à l'aide de `@params` dans les docstring
- le Snake est hard-codé à la dernière ligne `registerActions("../Test/Snake/")`

Code pylint : 5.56/10

**Comment by mcoudriau** [comment]
Hardcodé quelle médisance ! C'est un reste d'un vieux test à supprimer...
