### ISSUE TITLE
[Review] plugins/chat.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#13]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/master/src/plugins/chat.py) est bien commenté mais il manque quelques détails : 
- docstring pour module, classe et les deux méthodes (`@params` pour définir les paramètres)

Code pylint : 8.33/10

**Comment by Gu1nness** [comment]
Fixed by 2381402.
Rate is 10.0/10
