### ISSUE TITLE
[Review] plugins/chatcurses.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#14]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/master/src/plugins/chatcurses.py) est bien commenté mais il manque quelques détails : 
- C:  1, 0: Missing module docstring (missing-docstring)
- C:  5, 0: Missing class docstring (missing-docstring)
- C: 19, 4: Missing method docstring (missing-docstring)

Code pylint : 6.73/10

**Comment by Gu1nness** [comment]
Fixed by 2d82c33
The missing docstrings have been added.
