### ISSUE TITLE
[Review] server.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#15]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/master/src/server.py) est bien commenté mais il manque quelques détails : 
```
parser.add_argument("-p", "--path", default=PATH,
     help="Path of the game directory, should contain game.xml."
    "If this argument is not present, const.py will be used.")
```
`help` contient deux chaines de caractères ? 

Code pylint : 7.86/10

**Comment by Gu1nness** [comment]
Fixed by adb4dff51289f712ebfa92e1d6cb4e14f5371f33.
I also removed some unused import.
The code rate has been updated to 8.86/10, and I couldn't improve this more since it would have changed a lot a stuff everywhere (object attributes from the server would have been changed...)
