### ISSUE TITLE
[Rapport]

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#16]
# Sommaire du rapport 
On pourrait distinguer une partie **projet** d'une partie **méta**, où l'on prends du recul sur le projet.
### 1. Partie projet 
- décrire les objectifs du projet initial 
- décrire le monde dans lequel on joue -> lien avec le XML
- Lien entre Client et serveur -> partie réseau 
- Partie interface : pygame et ncurses 
- Editeur 
- Conventions, documentation & tests  (@JulesKzl)
### 2. Partie méta, feedback
- difficultés, problèmes de comptabilité (411...)
- remarques
- architecture à changer 
- projet soutenable à moyen/long terme ? 

# Organisation des tâches
On pourrait se séparer les tâches pour la partie 1, et tous répondre aux questions de la partie 2 puis mettre en commun ce qu'on pense pour dégager des difficultés, des remarques, etc ...

**Comment by Gu1nness** [comment]
Pour la partie projet, je m'occupe de la présentation du parsing du xml et de la description
des objets. @mcoudriau Comme tu as bossé sur la boucle principale, on se synchro pour faire un truc commun dessus ?

**Comment by ismailbennani** [comment]
- Pour le projet initial on s'en tient au contrat ([mkRPG/spec.tex@spec](https://github.com/mkRPGDev/mkRPG/blob/spec/spec.tex)), je vois pas trop ce qu'on peut faire comme slides mis à part reprendre les points uns par uns (ou peut être les séparer en points respectés et non respectés).

- Pour l'interface pygame, des remarques en vrac :
  - Très efficace pour mettre en place un cadre de travail rapidement, API directement calquée sur la SDL
  - Gros problèmes de compatibilités, il faut avoir LA bonne version par rapport a python etc, certains ont eu du mal à faire tourner pygame sur certaines machines (411 même si c'est plus lié aux limitations des utilisateurs)
  - Pas adapté à des projets de moyenne envergure comme le notre : (gros) problème de FPS et d'optimisation du code en général, les éléments de bases ne sont pas suffisamment documentés pour des utilisations avancées (héritage de classes de base pygame)
  - On aurait dû dès le départ mettre plus d'effort sur pygame (le plus gros du travail a été fait sur la partie représentation du monde etc au début, j'étais seul a bosser sur l'interface c'était peut être pas le meilleur des choix, on aurait pu être plus efficace)
  - Grosses difficultés pour faire des tests sur tout l'aspect graphique (pas spécifique à pygame), on s'est juste convaincu que les choses s'affichaient à peu près comme on le voulait sans plus

- Pour l'interface pygame, les points clefs du travail/les features fonctionnelles :
  - features : 
    - mise en cache (plus subtile depuis la refonte) des différents éléments graphiques
    - système de chunks poussé à l’extrême (seule les cases pertinentes sont prises en compte)
    - changement de cartes possibles
    - rotation de carte
    - zoom/dezoom
    - affichage d'objets (personnages, objets interactifs etc..) fonctionnel (cf pomme du snake), on ne peut pas modifier leur apparence lorsqu'on passe la souris dessus ou déclencher un événement au clique mais ces fonctionnalités peuvent être ajoutées très facilement (création de méthodes pour ça dans la bonne classe)
    - modifications de l'affichage gérées à travers les ordres du serveur (cf partie orders)
    - système de gui fonctionnel (cf croix directionnelle sur le snake), il manque le lien entre xml de description et gui mais on peut créer des fenêtres à la main. Il n'y a que très peu d'éléments disponibles (bouton, zone de texte, zone de texte cliquable et conteneur), mais c'est facile d'en rajouter, il suffit de suivre le même schéma que les précédents et de préférence de garder les même notations pour le style des éléments.
  - plugins permettant de faire à peu près tout ce qu'on veut sur l'affichage : accès total aux fonctions d'affichage, possibilité d'ajout de classes spécifiques à certaines choses, possibilité de contrôler la carte (cf croix directionnelles sur le snake qui permettent de tourner la carte dans deux directions)
  - toute l'interface (hors gui) n'est qu'une interprétation de fichiers xml -> paramétrable à souhait dans la limite des fonctionnalités implémentées, ajout de fonctionnalités possible via plugin
  - performances : raisonnables, le jeu tourne à 30 FPS sur une machine correcte, quelques lags quand on affiche des parties trop importantes de la map
  - stabilité : éviter de trop jouer avec les rotations de carte, il reste encore quelques exceptions non capturées, mis à part ça affichage très stable, aucun crash

- projet soutenable à moyen/long terme, partie interface pygame : depuis refonteClient, l'architecture de l'interface est beaucoup plus cohérente et pratique à utiliser, les fonctions présentes n'ont plus trop besoin d'être modifier (sauf peut-être pour optimiser certains calculs) et il ne reste plus qu'à rajouter les fonctionnalités souhaitées. L'interface est facilement soutenable à moyen terme, peut-être à long terme. Le seul problème étant qu'on ne peut pas faire de gros jeu avec ce système, ce qui est dû aux limitations de pygame.

- remarques personnelles : 
  - j'ai beaucoup aimé travailler sur ce projet, j'ai trouvé ça intéressant et marrant à faire
  - malgré quelques problèmes de communication/coordination en cours de route (et de gestion de branches .. :p) je trouve qu'on a plutôt bien travaillé ensemble
  - cachan s'appelle maintenant paris-saclay, désolé pour vous les gars (remarque trop personnelle ?)
  - gros problème de partage des taches, on en a sur-estimé certaines, sous-estimé d'autres, certains se sont retrouvé sans tâches à faire malgré nos quelques tentatives de se donner du travail à faire pour la semaine, ce qui fait que tout le monde n'a pas pu fournir autant d'effort qu'il aurait pu/voulu (je pense que ça nous concerne tous, pas seulement ceux qui se sont retrouvés dans ce cas)

Voila pour le contenu de la partie qui me concerne le plus, n'hésitez pas à me corriger, à compléter ce que je dis voire même à réfuter ce que je raconte (Marc fais toi plaisir).
En ce qui concerne les slides on fait chacun un beamer de notre coté et quelqu'un s'occupe de la mise en commun ou comment on fait ?

**Comment by Gu1nness** [comment]
Pour les slides, j'ai commencé à écrire celles sur ma partie (aka le parsing, donc en même temps le format des fichiers xml.)
Je finis cet aprem.

Ce qu'il faut préparer, c'est la partie commune sur le méta et les specs.
On peut pour le fichier final faire chacun un fichier en ```.tex``` et on fusionne tout dans des énormes slides ?

Il faut aussi se décider de l'ordre de présentation (quand fait-on la démo du jeu ? Quel jeu présente-t-on ? Fait-on une démo de l'éditeur ? (Je suis pour, à voir si @BaptP a envie de le faire !)

**Comment by BaptP** [comment]
J'ai créé la branche présentation, qui contient un début de beamer.

**Comment by BaptP** [comment]
Je compte bien montrer l'éditeur à un moment, mais il me parait difficile de lui faire cracher le jeu que l'on exécute immédiatement après.

**Comment by mcoudriau** [comment]
Au moins un demi-jeu !

**Comment by mcoudriau** [comment]
Bravo et merci à tous !
