### ISSUE TITLE
[commentaires] interface/map.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#2]
Le fichier [map.py](https://github.com/mkRPGDev/mkRPG/blob/master/src/interface/map.py) n'est pas commenté. 
- docstring de début de package manquant 
- la classe `MapViewer`, ainsi que toutes ses fonctions (`__init__`, `load_chunks`, `make_walkables`, `zoom`, `move`, `render`, `onscreen_chunks`, `update`, `update_chunks`, `propagate_trigger`, `compute_path` et `load_bg`) ne sont pas commentés. 

240 lignes sans commentaires, bon courage pour tout recommenter ! :) 

Score Pylint : 4.63/10 (exécutez `pylint map.py`)

**Comment by Gu1nness** [comment]
The current version of the GUI is in the branch refonteClient, and the file seems to be [this one](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/interface/pgcli.py).

There is little documentation, however it is not complete, for exemple [this function](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/interface/pgcli.py#L223) is left undocumented.

This should be done today if I have enough time.

**Comment by ismailbennani** [comment]
Obsolete
