### ISSUE TITLE
[Editor] Compilation failure

### ISSUE THREAD

**Issue by LCBH** [mkRPGDev/mkRPG#3]
When compiling the editor (` qtcreator RPGEditor.pro`) from the master branch, the following error pops out:
```
../editor/GUI/Tabs/ObjectEditors/mapeditors.h:5:26: fatal error: ui_mapeditor.h: Aucun fichier ou dossier de ce type
````

**Comment by mcoudriau** [comment]
C'est une errerur de nom qui semble traîner depuis quelques commits, elle contamine toutes les dernières version de l'éditeur. Elle est maintenant corrigée dans editor et master. Pour xml_export, chez moi l'éditeur compile mais au lancement rien ne s'affiche.

**Comment by mcoudriau** [comment]
L'éditeur de _xml_export_ fonctionne correctement suite à  f04ecf514e996a47fbce443a873835163b5cc9c8.
