### ISSUE TITLE
[Server] Clients not sync. in snake

### ISSUE THREAD

**Issue by LCBH** [mkRPGDev/mkRPG#4]
Following instructions from  the [README of Snake](https://github.com/mkRPGDev/mkRPG/tree/master/test/snake/README), the two ncurses interfaces do not show the same map (apple is missing on one of them). Therefore, it seems clients' states are not correctly synchronized.

**Comment by mcoudriau** [comment]
Je n'ai pas réussi à reproduire le bug ce matin. Le serveur avait bien été relancé avant l'ouverture des deux clients ?

**Comment by LCBH** [comment]
Voici une des façons d'observer ce comportement: lancer un serveur et deux clients, quitter un client et reconnecter ce client.

**Comment by mcoudriau** [comment]
Oui, c'est du au fait que le serveur démarre dès que les deux premiers clients sont connectés et qu'il n'existe pour l'instant pas de synchronisation en cours de jeu donc pas de moyen pour le 3ème client à être connecté de récupérer l'état actuel. Dans un premier temps je vais probablement seulement afficher un message pour empêcher ce troisième client de se lancer car je me concentre sur l'exemple minimal avec pygame (la branche server contient actuellement une version qui fait bouger l'entité de _simple_ mais les performances sont insuffisantes pour _snake_). Le problème pourra ensuite être réglé en partenariat avec le _laucher_.

**Comment by mcoudriau** [comment]
La synchronisation fonctionne pour les deux exemples sur la branche refonteClient.
