### ISSUE TITLE
[Review] shared/orders.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#8]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/shared/orders.py) est bien commenté mais il manque quelques détails : 
- un docstring de description global du module 
- des détails sur l'utilisation de IntEnum au sein du code 

Code pylint : 0.49/10 (surtout dû à l'utilisation de IntEnum, donc pas si grave)

**Comment by Gu1nness** [comment]
Commit 8f0c593 updates this issue.
The docstring has been added, but not the precisions on the IntEnum.
@mcoudriau could you please do this ? This is your module, I don't know it well enough to do so :)
