### ISSUE TITLE
[Review] shared/world.py

### ISSUE THREAD

**Issue by JulesKzl** [mkRPGDev/mkRPG#9]
Ce [fichier](https://github.com/mkRPGDev/mkRPG/blob/refonteClient/src/shared/world.py) est bien commenté mais il manque quelques détails : 
- un docstring de description global du module 
- quelques docstring de fonctions
- des imports inutiles selon pylint

Code pylint : 5.13/10 (surtout dû aux noms de variables de type `x1, y1`, mais c'est tout à fait normal)

**Comment by mcoudriau** [comment]
Hum, random par exemple est considéré inutile mais c'est pour permettre son utilisation depuis le Xml =).

**Comment by ismailbennani** [comment]
Ajout de quelques docstring, quelques modifications pour respecter les conventions : 65466ec72d89cdc2af2b1288194e0c8f70e21321

Code pylint : 6.02/10 (surtout dû aux noms de variables de type x1, y1)
